title: Wilson Truong
description: > # this means to ignore newlines until "baseurl:"
  My portfolio site!
permalink: ':title/'
baseurl: '/' # the subpath of your site, e.g. /blog
url: "http://wilsontruong.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: wilson truong # add your name
author-img:   # add your photo
about-author: an interaction designer who is focused on ui and games # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github:  # add your Github handle
social-linkedin: wiltruong # add your Linkedin handle
social-email: hello@wilsontruong.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
